import { describe, expect, it } from 'vitest'
import { existsSync, readFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
/*
 * Le script est du JavaScript pur : il doit tourner sous `node` avant toute
 * étape de compilation — c'est justement son rôle, s'exécuter avant Gradle.
 * TypeScript n'a donc pas de déclarations pour lui, et `@ts-expect-error`
 * porte sur la LIGNE du spécificateur de module, pas sur le mot `import`.
 */
import {
  lignePlausible,
  lignesSuspectes,
  FICHIERS,
  // @ts-expect-error — script Node en JS pur, sans déclarations de types.
} from './verifier-gradle.mjs'

describe('reconnaître un copier-coller égaré dans un script Gradle', () => {
  it('accepte ce qui ressemble à du Groovy', () => {
    for (const ligne of [
      "include ':app'",
      "apply from: 'capacitor.settings.gradle'",
      'android.useAndroidX=true',
      '    signingConfig signingConfigs.release',
      'def versionNpm = new groovy.json.JsonSlurper()',
      '',
      '    ',
      '// DO NOT EDIT THIS FILE!',
      '/* commentaire */',
      ' * suite de commentaire',
      '# org.gradle.parallel=true',
    ]) {
      expect(lignePlausible(ligne), ligne).toBe(true)
    }
  })

  it('REFUSE la ligne exacte qui a fait échouer la construction', () => {
    // Relevée telle quelle sur le poste : le chemin du JDK, collé nu dans
    // settings.gradle pendant le dépannage de l'étape précédente.
    expect(lignePlausible('"C:\\Program Files\\Eclipse Adoptium\\jdk-21.0.12.101-hotspot"')).toBe(
      false,
    )
  })

  it('REFUSE un chemin Windows nu, avec ou sans guillemets', () => {
    expect(lignePlausible('C:\\Program Files\\Java\\jdk-21')).toBe(false)
    expect(lignePlausible('C:/Program Files/Java/jdk-21')).toBe(false)
    expect(lignePlausible("'/usr/lib/jvm/java-21-openjdk'")).toBe(false)
  })

  it('rend le NUMÉRO de ligne, celui que Gradle affiche', () => {
    const contenu = [
      "include ':app'",
      "include ':capacitor-cordova-android-plugins'",
      '',
      "apply from: 'capacitor.settings.gradle'",
      '',
      '',
      '',
      '"C:\\Program Files\\Eclipse Adoptium\\jdk-21.0.12.101-hotspot"',
    ].join('\n')
    const suspectes = lignesSuspectes(contenu)
    expect(suspectes).toHaveLength(1)
    // Gradle disait « line: 8 ». Le script doit dire 8 aussi, sinon on
    // cherche au mauvais endroit.
    expect(suspectes[0]!.numero).toBe(8)
  })

  it('ne signale rien sur les fichiers RÉELS du dépôt', () => {
    /*
     * Deux garanties d'un coup, et il faut les deux :
     *
     *   • aucun FAUX POSITIF — si ce test tombe alors que le dépôt est sain,
     *     c'est le vérificateur qui est trop strict, et il ferait perdre à
     *     tout le monde le temps qu'il prétend faire gagner ;
     *   • aucune ligne égarée COMMISE. Le fichier qui a cassé la
     *     construction est versionné : poussé, il casse tous les postes. Ce
     *     test tourne en CI, donc la ligne ne peut pas passer la porte.
     */
    expect(FICHIERS.length).toBeGreaterThan(0)
    let lus = 0
    for (const relatif of FICHIERS as string[]) {
      const chemin = fileURLToPath(new URL(`../android/${relatif}`, import.meta.url))
      // `android/` n'existe qu'après `cap add android` : son absence n'est
      // pas une anomalie, et on ne fabrique pas une erreur là où il n'y a rien.
      if (!existsSync(chemin)) continue
      lus += 1
      expect(lignesSuspectes(readFileSync(chemin, 'utf8')), relatif).toEqual([])
    }
    expect(lus, 'aucun script Gradle lu — le test ne prouverait rien').toBeGreaterThan(0)
  })

  it('tolère les fins de ligne Windows', () => {
    expect(lignesSuspectes("include ':app'\r\napply from: 'x.gradle'\r\n")).toHaveLength(0)
  })
})
